site_name: Sample 2
repo_url: https://github.com/A-Baji/mk-docs-sample2
repo_name: Sample 2 Repo
theme:
  name: material

extra:
  version:
    provider: mike

edit_uri: /blob/master/
nav:
  - Home: index.md
